export const equipe = [
  {
    id: 1,
    nome: "Felipe Morales",
    cargo: "Desenvolvedor Backend - Gestor de Projetos",
    instagram: "https://www.instagram.com/fe.moraless/",
    github: "https://github.com/FelipeMoralesdev",
    linkedin: "https://www.linkedin.com/in/felipemoraless/",
    imagem: "/assets/team/felipe.jpeg",
  },
  {
    id: 2,
    nome: "Gabriela Godoi",
    cargo: "Desenvolvedora Full Stack",
    instagram: "https://www.instagram.com/igwabriela",
    github: "https://github.com/gabrielagodoi",
    linkedin: "https://www.linkedin.com/in/gabriela-godoi-a434bb18a",
    imagem: "/assets/team/gabriela.jpeg",
  },
  {
    id: 3,
    nome: "Luana Belmiro",
    cargo: "Desenvolvedora Full Stack - Design UI UX",
    instagram: null,
    github: "https://github.com/LUANABELMIRO",
    linkedin: "https://www.linkedin.com/in/luana-belmiro-8a3300239/",
    imagem: "/assets/team/luana.jpeg",
  },
  {
    id: 4,
    nome: "Marcelle De Oliveira",
    cargo: "Desenvolvedora Frontend",
    instagram: null,
    github: "https://github.com/Marcelle-1",
    linkedin: "https://www.linkedin.com/in/marcelle-oliveira/",
    imagem: "/assets/team/marcelle.jpeg",
  },
  {
    id: 5,
    nome: "Nicolas Braga",
    cargo: "Desenvolvedor Full Stack",
    instagram: "https://www.instagram.com/nclsbraga_dev",
    github: "https://github.com/nbraga",
    linkedin: "https://www.linkedin.com/in/nbraga2022",
    imagem: "/assets/team/nicolas.jpg",
  },
  {
    id: 6,
    nome: "Poliana Yukie",
    cargo: "Desenvolvedora Full Stack",
    instagram: "https://www.instagram.com/polianayukietasaka/",
    github: "https://github.com/PolianaYukie",
    linkedin: "https://www.linkedin.com/in/poliana-yukie-tasaka-275376b0",
    imagem: "/assets/team/poliana.jpeg",
  },
];
