export const parceiros = [
  {
    id: 1,
    nome: "Alessandra Marques",
    cargo: "Psicóloga e Graduanda em Pedagogia",
    imagem: "/assets/participantes/alessandra.jpg",
  },
  {
    id: 2,
    nome: "Tatiane Fernandes",
    cargo: "Engenheira de Produção Cultural",
    imagem: "/assets/participantes/tatiane.jpeg",
  },
  {
    id: 3,
    nome: "Eric Max",
    cargo: "Artivista, Ator e Produtor Cultural",
    imagem: "/assets/participantes/eric.jpeg",
  },
  {
    id: 4,
    nome: "Gabriela Amorim",
    cargo: "Data Analyst",
    imagem: "/assets/participantes/gabriela.jpeg",
  },
  {
    id: 5,
    nome: "Mariana Almeida",
    cargo: "Professora de Engenharia Econômica",
    imagem: "/assets/participantes/mariana-almeida.jpg",
  },
  {
    id: 6,
    nome: "Mariana Zancanaro",
    cargo: "Brand Strategist",
    imagem: "/assets/participantes/mariana-zancanaro.jpeg",
  },
  {
    id: 7,
    nome: "Luiza Ribeiro",
    cargo: "Psicóloga",
    imagem: "/assets/participantes/luiza.jpeg",
  },
  {
    id: 8,
    nome: "Diego Guedes",
    cargo: "Account Mananger",
    imagem: "/assets/participantes/diego.jpeg",
  },
  {
    id: 9,
    nome: "Renan Francisco",
    cargo: "Programador Full Stack",
    imagem: "/assets/participantes/renan.jpeg",
  },
  {
    id: 10,
    nome: "Andréia Rodrigues",
    cargo: "Pós-graduada em Arte Educação",
    imagem: "/assets/participantes/andreia.jpeg",
  },
  {
    id: 11,
    nome: "Juliana de Paula",
    cargo: "Professora Educação Infantil",
    imagem: "/assets/participantes/juliana.jpeg",
  },
  {
    id: 12,
    nome: "Thais Novaes",
    cargo: "Professora Ensino Fundamental",
    imagem: "/assets/participantes/thais.jpeg",
  },
  {
    id: 13,
    nome: "Cássia Ferreira",
    cargo: "Educadora Educação Infantil",
    imagem: "/assets/participantes/cassia.jpeg",
  },
  {
    id: 14,
    nome: "Bianca Figueredo",
    cargo: "Educadora Educação Popular",
    imagem: "/assets/participantes/bianca.jpeg",
  },
  {
    id: 15,
    nome: "Maria Carolina",
    cargo: "Produtora Multimída",
    imagem: "/assets/participantes/maria-carolina.jpeg",
  },
  {
    id: 16,
    nome: "Maria Clara",
    cargo: "Cientista Social e Fotógrafa",
    imagem: "/assets/participantes/maria-clara.jpeg",
  },
  {
    id: 17,
    nome: "Lucas Lima",
    cargo: "Biológo",
    imagem: "/assets/participantes/lucas.jpeg",
  },
  {
    id: 18,
    nome: "Filipe Davi",
    cargo: "Desenvolvedor Web",
    imagem: "/assets/participantes/filipe.jpeg",
  },
  {
    id: 19,
    nome: "Beethoven Lima",
    cargo: "Analista de Projetos e Analista de Sistemas",
    imagem: "/assets/participantes/beethoven.jpg",
  },
  {
    id: 20,
    nome: "Gustavo Melo",
    cargo: "Artista",
    imagem: "/assets/participantes/gustavo.jpeg",
  },
];
